
platform :ios, '12.0'
use_frameworks!

def portals_pods
    pod 'Capacitor'
    pod "CapacitorCamera"
    pod 'IonicPortals', :path => '../../../ionic-portals/ios/IonicPortals'
    pod 'IonicLiveUpdates', :path => '../../../live-updates-sdk/ios/LiveUpdatesSDK'
end

target 'Ecommerce' do
  portals_pods
end

target 'EcommerceTests' do
  portals_pods
end
